import type { Metadata } from 'next'
import { Roboto_Slab } from 'next/font/google'
import './globals.css'


const roboto = Roboto_Slab({
  subsets: ['latin'],
  variable: '--font-roboto',
  weight: ['300','400','700']
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="vi" className={roboto.className}>
      <body>{children}</body>
    </html>
  )
}
